### ISSUE TITLE
Get Travis-CI working

### ISSUE THREAD

**Issue by russplaysguitar** [russplaysguitar/UnderscoreCF#40]
See: https://github.com/marcins/cfml-ci

**Comment by russplaysguitar** [comment]
@ericlynnpeterson is currently working on this. see: https://github.com/ericlynnpeterson/UnderscoreCF

**Comment by ericlynnpeterson** [comment]
Hey, quick question.  It doesn't look like closures are supported in CF9 or earlier.  That means this library isn't supported in CF9 or earlier.  That's fine, but I wanted to double check here before removing the CF9 test case from TravisCI.

Also, it looks like testBind is failing on Railo 4.1 and 4.2.  Can anyone else confirm that?  I want to make sure the library is failing and not my TravisCI build.

Thanks.

**Comment by ericlynnpeterson** [comment]
The pull request is open at https://github.com/russplaysguitar/UnderscoreCF/pull/48.

**Comment by russplaysguitar** [comment]
I guess I should probably finish the integration on Travis-CI's site and add a build status image to the readme before closing this.
